context := "colima-shared"
tailscale := "/Applications/Tailscale.app/Contents/MacOS/Tailscale"
serve_port := "8766"
internal_port := "18766"
volumes_dir := join(env("HOME"), ".volumes", "wallabag")

default:
    @just --list

init:
    mkdir -p {{volumes_dir}}/data {{volumes_dir}}/images

up: init
    docker --context {{context}} compose up -d

down:
    docker --context {{context}} compose down

restart:
    docker --context {{context}} compose restart

logs:
    docker --context {{context}} compose logs -f

ps:
    docker --context {{context}} compose ps

pull:
    docker --context {{context}} compose pull

shell:
    docker --context {{context}} compose exec wallabag sh

bootstrap:
    @./scripts/bootstrap.sh

serve:
    {{tailscale}} serve --bg --https={{serve_port}} http://localhost:{{internal_port}}

backup: down && up
    @../scripts/backup.sh wallabag

restore tarball:
    @../scripts/restore.sh wallabag {{tarball}}
