mod adguard
mod freshrss
mod homebridge
mod wallabag

default:
    @just --list

up-all:
    just adguard up
    just freshrss up
    just homebridge up
    just wallabag up

down-all:
    just wallabag down
    just homebridge down
    just freshrss down
    just adguard down

ps-all:
    just adguard ps
    just freshrss ps
    just homebridge ps
    just wallabag ps

pull-all:
    just adguard pull
    just freshrss pull
    just homebridge pull
    just wallabag pull

backup-all:
    just adguard backup
    just freshrss backup
    just homebridge backup
    just wallabag backup
    @./scripts/backup-rotate.sh

backup-install:
    @./scripts/backup-install.sh

vm-shared-up:
    colima start -p shared

vm-shared-down:
    colima stop -p shared

vm-bridged-up:
    colima start -p bridged

vm-bridged-down:
    colima stop -p bridged

vm-agents-up:
    colima start -p agents

vm-agents-down:
    colima stop -p agents

bridged-ip-changed:
    @./scripts/bridged-ip-changed.sh

doctor:
    @./scripts/doctor.sh
