mod adguard
mod freshrss
mod wallabag

default:
    @just --list

up-all:
    just adguard up
    just freshrss up
    just wallabag up

down-all:
    just wallabag down
    just freshrss down
    just adguard down

ps-all:
    just adguard ps
    just freshrss ps
    just wallabag ps

pull-all:
    just adguard pull
    just freshrss pull
    just wallabag pull

vm-default:
    colima start -p default

vm-adguard:
    colima start -p adguard

vm-up: vm-default vm-adguard
