tap "homebrew/bundle"
tap "homebrew/core"
tap "1password/tap"

brew "neovim"
brew "irssi"
brew "ripgrep"
brew "fd"

cask "firefox"
cask "1password"
cask "1password-cli"
cask "iterm2"
cask "dwarf-fortress"

